[package]
name = "cantaloupe"
version = "1.0.0"
authors = ["Jonathan Vasquez <jon@xyinn.org>"]
edition = "2021"
license = "BSD-2-Clause"
description = "A simple backup replication tool for OpenZFS."

[dependencies]
clap = { version = "4.0.4", features = ["cargo", "derive"] }
